### ISSUE TITLE
Embed\Http\NetworkException Error code 23

### ISSUE THREAD

**Issue by benfeather** [benjamminf/craft-embedded-assets#262]
### What question would you like to ask?

I'm getting this error when trying to add an embeded asset using this plugin.

Craft CMS: 5.1.10
PHP: 8.3.8

I'm not sure what's causing the issue, curl is installed and enabled:

![CleanShot 2024-06-12 at 14 07 31@2x](https://github.com/spicywebau/craft-embedded-assets/assets/43571410/5cc57d9b-3283-47f4-a692-c281a6aca80c)

Any help would be appreciated.

```
Embed\Http\NetworkException in /var/www/tepari.cms/vendor/embed/embed/src/Http/CurlDispatcher.php:165
Stack trace:
#0 /var/www/tepari.cms/vendor/embed/embed/src/Http/CurlDispatcher.php(126): Embed\Http\CurlDispatcher->error()
#1 /var/www/tepari.cms/vendor/embed/embed/src/Http/CurlDispatcher.php(38): Embed\Http\CurlDispatcher->getResponse()
#2 /var/www/tepari.cms/vendor/embed/embed/src/Http/CurlClient.php(31): Embed\Http\CurlDispatcher::fetch()
#3 /var/www/tepari.cms/vendor/embed/embed/src/Http/Crawler.php(56): Embed\Http\CurlClient->sendRequest()
#4 /var/www/tepari.cms/vendor/embed/embed/src/Embed.php(24): Embed\Http\Crawler->sendRequest()
#5 /var/www/tepari.cms/vendor/spicyweb/craft-embedded-assets/src/Service.php(172): Embed\Embed->get()
#6 /var/www/tepari.cms/vendor/spicyweb/craft-embedded-assets/src/Service.php(79): spicyweb\embeddedassets\Service->_getDataFromEmbed()
#7 /var/www/tepari.cms/vendor/spicyweb/craft-embedded-assets/src/Controller.php(207): spicyweb\embeddedassets\Service->requestUrl()
#8 [internal function]: spicyweb\embeddedassets\Controller->actionPreview()
#9 /var/www/tepari.cms/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#10 /var/www/tepari.cms/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#11 /var/www/tepari.cms/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#12 /var/www/tepari.cms/vendor/craftcms/cms/src/web/Application.php(349): yii\base\Module->runAction()
#13 /var/www/tepari.cms/vendor/craftcms/cms/src/web/Application.php(650): craft\web\Application->runAction()
#14 /var/www/tepari.cms/vendor/craftcms/cms/src/web/Application.php(311): craft\web\Application->_processActionRequest()
#15 /var/www/tepari.cms/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest()
#16 /var/www/tepari.cms/web/index.php(12): yii\base\Application->run()
#17 {main} {"memory":11080304,"exception":"[object] (Embed\\Http\\NetworkException(code: 23):  at /var/www/tepari.cms/vendor/embed/embed/src/Http/CurlDispatcher.php:165)"} 
```

**Comment by ttempleton** [comment]
It seems that there was a [bug in cURL 8.7.1](https://github.com/curl/curl/issues/13209) that could cause error code 23 in some circumstances, so it would be worth upgrading it to 8.8.0 if possible.
