### ISSUE TITLE
Issue with Twitter/X:  Maximum (10) redirects followed

### ISSUE THREAD

**Issue by arifje** [benjamminf/craft-embedded-assets#272]
### Bug Description

For some weeks now we can't embed X/Twitter links anymore. 

Error:

```
2024-09-27 11:55:26 [web.ERROR] [Embed\Http\NetworkException] Embed\Http\NetworkException: Maximum (10) redirects followed in /var/www/site/cms/vendor/embed/embed/src/Http/CurlDispatcher.php:165
Stack trace:
#0 /var/www/site/cms/vendor/embed/embed/src/Http/CurlDispatcher.php(126): Embed\Http\CurlDispatcher->error()
#1 /var/www/site/cms/vendor/embed/embed/src/Http/CurlDispatcher.php(38): Embed\Http\CurlDispatcher->getResponse()
#2 /var/www/site/cms/vendor/embed/embed/src/Http/CurlClient.php(31): Embed\Http\CurlDispatcher::fetch()
#3 /var/www/site/cms/vendor/embed/embed/src/Http/Crawler.php(56): Embed\Http\CurlClient->sendRequest()
#4 /var/www/site/cms/vendor/embed/embed/src/Embed.php(24): Embed\Http\Crawler->sendRequest()
#5 /var/www/site/cms/vendor/spicyweb/craft-embedded-assets/src/Service.php(184): Embed\Embed->get()
#6 /var/www/site/cms/vendor/spicyweb/craft-embedded-assets/src/Service.php(79): spicyweb\embeddedassets\Service->_getDataFromEmbed()
#7 /var/www/site/cms/vendor/spicyweb/craft-embedded-assets/src/Controller.php(207): spicyweb\embeddedassets\Service->requestUrl()
#8 [internal function]: spicyweb\embeddedassets\Controller->actionPreview()
#9 /var/www/site/cms/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#10 /var/www/site/cms/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#11 /var/www/site/cms/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#12 /var/www/site/cms/vendor/craftcms/cms/src/web/Application.php(341): yii\base\Module->runAction()
#13 /var/www/site/cms/vendor/craftcms/cms/src/web/Application.php(640): craft\web\Application->runAction()
#14 /var/www/site/cms/vendor/craftcms/cms/src/web/Application.php(303): craft\web\Application->_processActionRequest()
#15 /var/www/site/cms/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest()
#16 /var/www/site/cms/web/index.php(30): yii\base\Application->run()
#17 {main} {"memory":8289624,"exception":"[object] (Embed\\Http\\NetworkException(code: 47): Maximum (10) redirects followed at /var/www/site/cms/vendor/embed/embed/src/Http/CurlDispatcher.php:165)"} 
2024-09-27 11:55:26 [web.INFO] [application] Request context:
$_GET = [
	'p' => 'cp/actions/embeddedassets/actions/preview'
	'site' => 'default'
	'showContent' => '1'
	'callback' => 'embeddedassetspyr39gnt2oq7'
	'url' => 'https://x.com/VincentOshana/status/1839458282349769102'
```

### Steps to reproduce

Embed a random X link

### Embedded Assets version

4.1.2

### Craft CMS version

4.12.4

**Comment by ttempleton** [comment]
This is likely being caused by https://github.com/oscarotero/Embed/issues/542. If it still isn't working with Embedded Assets, and you do a test directly with the Embed package and it works, please let me know and I'll reopen the issue.
